"""LLM Meteorological Explanation Generator for CycloSense prediction matrices."""

from __future__ import annotations

import json
import logging
import os
import re
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.config.ml_config import LLMExplanationConfig
from src.exceptions import CycloSenseError

logger = logging.getLogger(__name__)


class LLMExplanationError(CycloSenseError):
    """Raised when explanation generation encounters an unrecoverable failure."""


@dataclass(frozen=True)
class LLMExplanationResult:
    """Structured meteorological explanation generated by LLM from prediction matrices."""

    summary: str
    meteorological_rationale: str
    primary_drivers: list[str]
    inhibiting_factors: list[str]
    operational_guidance: str
    case_type: str  # "high_risk_verification" or "suppressed_or_low_risk"
    raw_response: dict[str, Any] | None = field(default=None, repr=False)

    def as_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary,
            "meteorological_rationale": self.meteorological_rationale,
            "primary_drivers": list(self.primary_drivers),
            "inhibiting_factors": list(self.inhibiting_factors),
            "operational_guidance": self.operational_guidance,
            "case_type": self.case_type,
        }


class LLMExplainer(ABC):
    """Abstract base class for generating meteorological explanations from ML matrices."""

    @abstractmethod
    def generate_explanation(
        self,
        prediction_payload: dict[str, Any],
        env_features: dict[str, float] | None = None,
    ) -> LLMExplanationResult:
        """Generate a structured meteorological explanation from prediction matrices."""
        raise NotImplementedError


class MockLLMExplainer(LLMExplainer):
    """Deterministic, rule-aware mock explainer for testing both >=50% and <50% scenarios."""

    def __init__(
        self,
        error: Exception | str | None = None,
    ) -> None:
        self.error = error
        self.call_count: int = 0
        self.calls: list[dict[str, Any]] = []

    def generate_explanation(
        self,
        prediction_payload: dict[str, Any],
        env_features: dict[str, float] | None = None,
    ) -> LLMExplanationResult:
        self.call_count += 1
        self.calls.append({
            "prediction_payload": dict(prediction_payload),
            "env_features": dict(env_features) if env_features else {},
        })

        if self.error:
            if isinstance(self.error, Exception):
                raise self.error
            if self.error == "timeout":
                raise LLMExplanationError("Mock explainer simulated timeout.")
            raise LLMExplanationError(f"Mock explainer error: {self.error}")

        env = env_features or {}
        signals_above_50 = bool(prediction_payload.get("all_signals_above_50", False))
        final_status = str(prediction_payload.get("final_status", "LLM_NOT_REQUIRED"))
        risk_index = float(prediction_payload.get("development_risk_index", 0.0))
        img_prob = float(prediction_payload.get("image_probability", 0.0))
        num_prob = float(prediction_payload.get("numerical_probability", 0.0))
        fusion_prob = float(prediction_payload.get("fusion_probability", 0.0))

        # Identify environmental drivers and inhibitors
        drivers: list[str] = []
        inhibitors: list[str] = []

        sst = env.get("sea_surface_temperature_c")
        if sst is not None:
            if sst >= 27.0:
                drivers.append(f"Favorable sea surface temperature ({sst:.1f}°C >= 26.5°C threshold)")
            else:
                inhibitors.append(f"Sub-optimal ocean heat content / SST ({sst:.1f}°C < 26.5°C)")

        shear = env.get("vertical_wind_shear_ms")
        if shear is not None:
            if shear > 20.0:
                inhibitors.append(f"Hostile vertical wind shear ({shear:.1f} m/s) preventing vertical alignment")
            else:
                drivers.append(f"Low vertical wind shear ({shear:.1f} m/s) permitting convective column retention")

        rh = env.get("relative_humidity_pct")
        if rh is not None:
            if rh >= 70.0:
                drivers.append(f"Moist mid-troposphere ({rh:.0f}% RH) fueling latent heat release")
            else:
                inhibitors.append(f"Dry air entrainment ({rh:.0f}% RH) suppressing convective towers")

        rot = env.get("rotation_index")
        if rot is not None:
            if rot >= 0.5:
                drivers.append(f"Elevated vorticity / rotation index ({rot:.2f})")
            else:
                inhibitors.append(f"Weak atmospheric vorticity / rotation index ({rot:.2f})")

        org = env.get("cloud_organization_index")
        if org is not None:
            if org >= 0.5:
                drivers.append(f"High cloud organization index ({org:.2f})")
            else:
                inhibitors.append(f"Disorganized cloud canopy ({org:.2f})")

        # ── Case A: High-risk verification triggered (all signals >= 50%) ─────
        if signals_above_50:
            case_type = "high_risk_verification"
            if final_status == "VERIFIED_CYCLONE":
                summary = (
                    f"Multimodal ML models and secondary visual verification confirm active cyclogenesis "
                    f"with a Development/Risk Index of {risk_index:.1f}/100."
                )
                rationale = (
                    f"All per-input prediction matrices exceed the 50% threshold "
                    f"(Visual={img_prob:.2f}, Numerical={num_prob:.2f}, Fusion={fusion_prob:.2f}). "
                    f"Satellite imagery exhibits pronounced spiral banding and curved convective structure, "
                    f"which is corroborated by favorable atmospheric parameters."
                )
                guidance = "Issue cyclone warning advisory and initiate standard tropical disturbance tracking protocol."
            elif final_status == "SECONDARY_REVIEW_CONFLICT":
                summary = (
                    f"Secondary review conflict detected: ML models show elevated signal ({fusion_prob:.2f}), "
                    f"but secondary visual verification identified benign/non-cyclonic cloud patterns."
                )
                rationale = (
                    f"While numerical and image feature activations exceed 50% "
                    f"(Visual={img_prob:.2f}, Num={num_prob:.2f}), detailed visual inspection confirmed "
                    f"that cloud formations lack cyclonic rotation and central organization. "
                    f"This indicates a benign cloud cluster or convective false positive."
                )
                guidance = "Do not issue cyclone alert. Retain disturbance under secondary surveillance without escalation."
            else:  # HUMAN_REVIEW_REQUIRED or LLM_VERIFICATION_FAILED
                summary = (
                    f"Elevated cyclone signals detected (Risk={risk_index:.1f}/100) requiring manual meteorological review."
                )
                rationale = (
                    f"Model prediction matrices indicate moderate-to-high cyclone probability "
                    f"(Visual={img_prob:.2f}, Num={num_prob:.2f}, Fusion={fusion_prob:.2f}), "
                    f"but verification resulted in {final_status}. Analyst triage is required to resolve structural ambiguity."
                )
                guidance = "Route observation to duty meteorologist for manual satellite inspection and radar cross-check."

        # ── Case B: Other case / Suppressed or Low Risk (signals < 50%) ────────
        else:
            case_type = "suppressed_or_low_risk"
            failing_signals = []
            if img_prob < 0.5:
                failing_signals.append(f"Visual Probability ({img_prob:.2f})")
            if num_prob < 0.5:
                failing_signals.append(f"Numerical Probability ({num_prob:.2f})")
            if fusion_prob < 0.5:
                failing_signals.append(f"Fusion Probability ({fusion_prob:.2f})")

            summary = (
                f"Cyclogenesis is suppressed or absent with a Development/Risk Index of {risk_index:.1f}/100. "
                f"Secondary LLM verification was not required."
            )
            rationale = (
                f"One or more prediction matrices fall below the 50% trigger threshold "
                f"({', '.join(failing_signals)}). "
                f"Atmospheric environmental conditions or visual cloud structures do not support organized cyclonic development. "
                f"Key suppressing factors include: {'; '.join(inhibitors) if inhibitors else 'neutral ambient conditions'}."
            )
            guidance = "Normal meteorological monitoring. No cyclone alert required."

        if not drivers:
            drivers.append("No prominent favorable cyclogenesis parameters observed.")
        if not inhibitors:
            inhibitors.append("No major suppressing barriers detected in ambient field.")

        return LLMExplanationResult(
            summary=summary,
            meteorological_rationale=rationale,
            primary_drivers=drivers,
            inhibiting_factors=inhibitors,
            operational_guidance=guidance,
            case_type=case_type,
            raw_response={"mock": True, "call_index": self.call_count},
        )


class GroqExplainer(LLMExplainer):
    """Generates structured meteorological explanations using Groq chat completions."""

    ENDPOINT = "https://api.groq.com/openai/v1/chat/completions"

    def __init__(
        self,
        api_key: str | None = None,
        model_name: str = "llama-3.3-70b-versatile",
        timeout_seconds: float = 15.0,
        max_retries: int = 2,
    ) -> None:
        key = api_key or os.environ.get("GROQ_API_KEY")
        self._api_key = key
        self.model_name = model_name
        self.timeout_seconds = timeout_seconds
        self.max_retries = max(0, max_retries)
        self._fallback_mock = MockLLMExplainer()

    def generate_explanation(
        self,
        prediction_payload: dict[str, Any],
        env_features: dict[str, float] | None = None,
    ) -> LLMExplanationResult:
        if not self._api_key:
            logger.info("GROQ_API_KEY unset; using deterministic mock explainer.")
            return self._fallback_mock.generate_explanation(prediction_payload, env_features)

        system_prompt = (
            "You are an expert meteorological AI assistant synthesizing tropical cyclone prediction matrices.\n"
            "Analyze the quantitative prediction matrices (probabilities, risk index, environmental variables, and verification status).\n"
            "Distinguish between two cases:\n"
            "  Case A (Signals >= 50%): Verification was triggered; explain the visual/numerical agreement, conflict, or uncertainty.\n"
            "  Case B (Signals < 50%): Verification was not required; explain the atmospheric barriers (e.g. shear, dry air, low SST) suppressing cyclogenesis.\n\n"
            "Return valid JSON only matching this schema:\n"
            "{\n"
            '  "summary": "<one sentence executive summary>",\n'
            '  "meteorological_rationale": "<paragraph synthesizing prediction matrices and atmospheric physics>",\n'
            '  "primary_drivers": ["<driver 1>", "<driver 2>"],\n'
            '  "inhibiting_factors": ["<barrier 1>", "<barrier 2>"],\n'
            '  "operational_guidance": "<concise triage recommendation>",\n'
            '  "case_type": "high_risk_verification" | "suppressed_or_low_risk"\n'
            "}"
        )

        user_content = (
            f"CYCLOSENSE PREDICTION MATRICES & CONTEXT:\n"
            f"{json.dumps(prediction_payload, indent=2)}\n\n"
            f"ENVIRONMENTAL FEATURES:\n"
            f"{json.dumps(env_features or {}, indent=2)}\n\n"
            "Synthesize these matrices and provide the structured meteorological explanation."
        )

        payload = {
            "model": self.model_name,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2,
            "max_tokens": 768,
        }

        body_bytes = json.dumps(payload).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self._api_key}",
            "User-Agent": "CycloSense-Explainer/1.0",
        }

        last_error: Exception | None = None
        for attempt in range(1 + self.max_retries):
            try:
                req = urllib.request.Request(self.ENDPOINT, data=body_bytes, headers=headers, method="POST")
                with urllib.request.urlopen(req, timeout=self.timeout_seconds) as resp:
                    resp_bytes = resp.read()
                    data = json.loads(resp_bytes.decode("utf-8"))

                content = data["choices"][0]["message"]["content"]
                return self._parse_json(content, raw=data)

            except Exception as err:
                last_error = err
                logger.warning("Groq explainer attempt %d/%d failed: %s", attempt + 1, 1 + self.max_retries, err)

        logger.warning("Groq explainer failed; falling back to rule-based explanation: %s", last_error)
        return self._fallback_mock.generate_explanation(prediction_payload, env_features)

    def _parse_json(self, content: str, raw: dict[str, Any]) -> LLMExplanationResult:
        text = content.strip()
        if "```" in text:
            match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
            if match:
                text = match.group(1)

        parsed = json.loads(text)
        return LLMExplanationResult(
            summary=str(parsed.get("summary", "")),
            meteorological_rationale=str(parsed.get("meteorological_rationale", "")),
            primary_drivers=[str(d) for d in parsed.get("primary_drivers", [])],
            inhibiting_factors=[str(i) for i in parsed.get("inhibiting_factors", [])],
            operational_guidance=str(parsed.get("operational_guidance", "")),
            case_type=str(parsed.get("case_type", "suppressed_or_low_risk")),
            raw_response=raw,
        )


def build_explainer(
    config: LLMExplanationConfig | None = None,
    api_key: str | None = None,
) -> LLMExplainer:
    """Factory creating an LLMExplainer based on config and environment."""
    cfg = config or LLMExplanationConfig.from_raw({})
    provider = cfg.provider.lower().strip()

    if provider == "groq":
        key = api_key or os.environ.get("GROQ_API_KEY")
        if key:
            return GroqExplainer(
                api_key=key,
                model_name=cfg.model_name,
                timeout_seconds=cfg.timeout_seconds,
                max_retries=cfg.max_retries,
            )
        return MockLLMExplainer()

    return MockLLMExplainer()
